import "server-only";
import type { IntakeQuestion } from "@/features/intake/types";

/**
 * Bump when the default questionnaire changes; published DB set is replaced on mismatch.
 * v5: Neutral / business-oriented wording (works for staff submitting on behalf of a business).
 */
export const INTAKE_QUESTIONS_VERSION = "v5-2026-05-01";

const SERVICES_Q = "services_requested";

export const INTAKE_QUESTIONS: IntakeQuestion[] = [
  // Section 0 - Business identity & contact (account holder name stays on the profile)
  {
    id: "business_name",
    section: "Business & contact",
    order: 1,
    prompt: "Business or brand name for this request",
    type: "short_text",
    required: true,
  },
  {
    id: "whatsapp",
    section: "Business & contact",
    order: 2,
    prompt: "WhatsApp number to reach for this project",
    type: "short_text",
    required: true,
  },
  {
    id: "email",
    section: "Business & contact",
    order: 3,
    prompt: "Primary email for correspondence on this request",
    type: "short_text",
    required: true,
  },
  {
    id: "city_state",
    section: "Business & contact",
    order: 4,
    prompt: "City and state where this business operates",
    type: "short_text",
    required: true,
  },

  // Section 1 - The business
  {
    id: "business_one_sentence",
    section: "The business",
    order: 5,
    prompt: "Describe this business in one sentence.",
    type: "paragraph",
    required: true,
  },
  {
    id: "industry",
    section: "The business",
    order: 6,
    prompt: "What industry is this business in?",
    type: "single_choice",
    required: true,
    options: [
      { value: "food_bev", label: "Food & Beverages" },
      { value: "fashion_retail", label: "Fashion & Retail" },
      { value: "health_pharmacy", label: "Health & Pharmacy" },
      { value: "beauty_lifestyle", label: "Beauty & Lifestyle" },
      { value: "education", label: "Education & Training" },
      { value: "logistics", label: "Logistics & Delivery" },
      { value: "real_estate", label: "Real Estate" },
      { value: "religious", label: "Religious Organisation" },
      { value: "hospitality", label: "Hospitality & Events" },
      { value: "finance_prof", label: "Finance & Professional Services" },
      { value: "startup_tech", label: "Startup / Tech" },
      { value: "ngo", label: "NGO / Non-profit" },
      { value: "other", label: "Other (please specify)" },
    ],
  },
  {
    id: "business_tenure",
    section: "The business",
    order: 7,
    prompt: "How long has this business been operating?",
    type: "single_choice",
    required: true,
    options: [
      { value: "starting", label: "Just starting out" },
      { value: "lt1y", label: "Less than 1 year" },
      { value: "1_3y", label: "1-3 years" },
      { value: "3_5y", label: "3-5 years" },
      { value: "5y_plus", label: "5+ years" },
    ],
  },
  {
    id: "team_size",
    section: "The business",
    order: 8,
    prompt: "How many people work in this business?",
    type: "single_choice",
    required: true,
    options: [
      { value: "solo", label: "Solo (one person)" },
      { value: "2_5", label: "2-5" },
      { value: "6_20", label: "6-20" },
      { value: "20_plus", label: "20+" },
    ],
  },
  {
    id: "current_assets",
    section: "The business",
    order: 9,
    prompt: "Does this business currently have any of the following? (tick all that apply)",
    type: "multi_choice",
    required: true,
    options: [
      { value: "website", label: "A website" },
      { value: "biz_email", label: "A business email" },
      { value: "online_pay", label: "An online payment method" },
      { value: "invoicing", label: "An invoicing system" },
      { value: "mobile_app", label: "A mobile app" },
      { value: "none", label: "None of the above" },
    ],
  },

  // Section 2 - Scope (drives Section 3)
  {
    id: SERVICES_Q,
    section: "Scope",
    order: 10,
    prompt: "Which service(s) should this request cover? (tick all that apply)",
    type: "multi_choice",
    required: true,
    options: [
      { value: "website_landing", label: "Website & Landing Page" },
      { value: "mobile_app", label: "Mobile App Development" },
      { value: "domain_hosting", label: "Domain & Hosting" },
      { value: "business_email", label: "Business Email" },
      { value: "payments_gateways", label: "Payments & Gateways" },
      { value: "invoicing_system", label: "Invoicing System" },
      { value: "bulk_messaging", label: "Bulk Messaging" },
      { value: "marketing_ads", label: "Marketing & Ads" },
      { value: "staff_training", label: "Staff Training" },
    ],
  },

  // Section 3A - Website & mobile (if Website or Mobile App selected)
  {
    id: "webapp_main_purpose",
    section: "Website & app details",
    order: 11,
    prompt: "Main purpose of the website or app for this project (tick all that apply)",
    type: "multi_choice",
    required: true,
    allowOther: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["website_landing", "mobile_app"] },
    options: [
      { value: "showcase", label: "Showcase the business / portfolio" },
      { value: "ecommerce", label: "Sell products online (e-commerce)" },
      { value: "bookings", label: "Bookings or appointments" },
      { value: "internal_ops", label: "Manage customers or orders internally" },
      { value: "other", label: "Other (please specify)" },
    ],
  },
  {
    id: "domain_already",
    section: "Website & app details",
    order: 12,
    prompt: "For this project, is a domain name already available?",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["website_landing", "mobile_app"] },
    options: [
      { value: "yes", label: "Yes, already registered" },
      { value: "no", label: "No, needs to be acquired" },
      { value: "unsure", label: "Not sure yet" },
    ],
  },
  {
    id: "branding_ready",
    section: "Website & app details",
    order: 13,
    prompt: "Are logo and brand colours already defined for this project?",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["website_landing", "mobile_app"] },
    options: [
      { value: "full", label: "Yes, full brand kit" },
      { value: "logo_only", label: "Logo only" },
      { value: "need_branding", label: "Branding still needed" },
    ],
  },
  {
    id: "content_ready",
    section: "Website & app details",
    order: 14,
    prompt: "Is written and visual content ready? (text, photos, product images)",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["website_landing", "mobile_app"] },
    options: [
      { value: "yes", label: "Yes, ready to use" },
      { value: "partial", label: "Partially ready" },
      { value: "no", label: "Content support needed" },
    ],
  },
  {
    id: "target_platforms",
    section: "Website & app details",
    order: 15,
    prompt: "Which platforms should this cover? (tick all that apply)",
    type: "multi_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["website_landing", "mobile_app"] },
    options: [
      { value: "android", label: "Mobile App (Android)" },
      { value: "ios", label: "Mobile App (iOS / iPhone)" },
      { value: "desktop_web", label: "Desktop browser" },
      { value: "mobile_web", label: "Mobile browser" },
    ],
  },
  {
    id: "inspiration_refs",
    section: "Website & app details",
    order: 16,
    prompt: "Example websites or apps to reference for look and feel? (links or names)",
    type: "paragraph",
    required: false,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["website_landing", "mobile_app"] },
  },

  // Section 3B - Payments
  {
    id: "payment_methods_want",
    section: "Payments & gateways",
    order: 17,
    prompt: "Which payment methods should this project support? (tick all that apply)",
    type: "multi_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["payments_gateways"] },
    options: [
      { value: "card", label: "Debit / Credit Card" },
      { value: "transfer", label: "Bank Transfer" },
      { value: "ussd", label: "USSD (*737#, *901#, etc.)" },
      { value: "pod", label: "Pay on Delivery" },
      { value: "bnpl", label: "Buy Now Pay Later" },
      { value: "unsure", label: "Not sure yet" },
    ],
  },
  {
    id: "payment_provider_status",
    section: "Payments & gateways",
    order: 18,
    prompt: "Is a payment service provider already set up for this business?",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["payments_gateways"] },
    options: [
      { value: "yes", label: "Yes, already set up" },
      { value: "no", label: "No, not yet" },
      { value: "unsure", label: "Not sure" },
    ],
  },

  // Section 3C - Invoicing
  {
    id: "current_invoicing",
    section: "Invoicing",
    order: 19,
    prompt: "How are invoices or receipts issued today?",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["invoicing_system"] },
    options: [
      { value: "whatsapp", label: "WhatsApp message" },
      { value: "handwritten", label: "Handwritten" },
      { value: "sheets", label: "Excel / Google Sheets" },
      { value: "other_tool", label: "Another tool (please specify)" },
      { value: "none", label: "Not issued today / not applicable" },
    ],
  },
  {
    id: "invoice_automation",
    section: "Invoicing",
    order: 20,
    prompt: "Should invoices go out automatically after each transaction?",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["invoicing_system"] },
    options: [
      { value: "yes_auto", label: "Yes, fully automated" },
      { value: "no_manual", label: "No, manual sending" },
      { value: "unsure", label: "Not sure yet" },
    ],
  },

  // Section 3D - Bulk messaging
  {
    id: "messaging_channels",
    section: "Bulk messaging",
    order: 21,
    prompt: "Which channels should this project use to reach customers? (tick all that apply)",
    type: "multi_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["bulk_messaging"] },
    options: [
      { value: "whatsapp", label: "WhatsApp" },
      { value: "email", label: "Email" },
      { value: "sms", label: "SMS" },
      { value: "unsure", label: "Not sure yet" },
    ],
  },
  {
    id: "contact_list_ready",
    section: "Bulk messaging",
    order: 22,
    prompt: "Is a customer contact list available for this work?",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["bulk_messaging"] },
    options: [
      { value: "ready", label: "Yes, organised and ready" },
      { value: "scattered", label: "Yes, split across tools or files" },
      { value: "fresh", label: "No, starting from scratch" },
    ],
  },

  // Section 3E - Marketing
  {
    id: "ad_platforms",
    section: "Marketing & ads",
    order: 23,
    prompt: "Which advertising platforms should this work cover? (tick all that apply)",
    type: "multi_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["marketing_ads"] },
    options: [
      { value: "meta", label: "Instagram / Facebook" },
      { value: "tiktok", label: "TikTok" },
      { value: "google", label: "Google" },
      { value: "unsure", label: "Not sure yet" },
    ],
  },
  {
    id: "ad_creative_ready",
    section: "Marketing & ads",
    order: 24,
    prompt: "Is ad creative (images or videos) already available?",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["marketing_ads"] },
    options: [
      { value: "yes", label: "Yes, assets ready" },
      { value: "no", label: "Creative production needed" },
    ],
  },

  // Section 3F - Staff training
  {
    id: "training_headcount",
    section: "Staff training",
    order: 25,
    prompt: "How many staff need to be trained?",
    type: "single_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["staff_training"] },
    options: [
      { value: "1_3", label: "1-3 staff" },
      { value: "4_10", label: "4-10 staff" },
      { value: "10_plus", label: "10+ staff" },
    ],
  },
  {
    id: "training_topics",
    section: "Staff training",
    order: 26,
    prompt: "What should the training cover? (tick all that apply)",
    type: "multi_choice",
    required: true,
    visibleWhen: { questionId: SERVICES_Q, anyOf: ["staff_training"] },
    options: [
      { value: "backend", label: "Using the website or app backend" },
      { value: "payments", label: "Processing payments" },
      { value: "invoices", label: "Sending invoices and receipts" },
      { value: "bulk", label: "Bulk messaging tools" },
      { value: "general_digital", label: "General digital tools and operations" },
    ],
  },

  // Section 4 - Timeline & budget
  {
    id: "timeline_ready",
    section: "Timeline & budget",
    order: 27,
    prompt: "Target timeframe for this work",
    type: "single_choice",
    required: true,
    options: [
      { value: "asap", label: "ASAP (within 2 weeks)" },
      { value: "month", label: "Within a month" },
      { value: "1_3mo", label: "1-3 months" },
      { value: "no_rush", label: "Flexible (prioritise quality)" },
    ],
  },
  {
    id: "budget_mind",
    section: "Timeline & budget",
    order: 28,
    prompt: "Budget range for this project (if known)",
    type: "single_choice",
    required: true,
    options: [
      { value: "ngn_200k_300k", label: "₦200,000-₦300,000" },
      { value: "ngn_400k_750k", label: "₦400,000-₦750,000" },
      { value: "ngn_750k_2m", label: "₦750,000-₦2,000,000" },
      { value: "ngn_2m_plus", label: "₦2,000,000+" },
      { value: "discuss_after_consultation", label: "Discuss after consultation" },
    ],
  },
  {
    id: "anything_else",
    section: "Timeline & budget",
    order: 29,
    prompt: "Anything else we should know about this build or scope?",
    type: "paragraph",
    required: false,
  },

  // Section 5 - Getting in touch
  {
    id: "contact_methods_pref",
    section: "Getting in touch",
    order: 30,
    prompt: "Preferred ways to follow up on this request (tick all that apply)",
    type: "multi_choice",
    required: true,
    options: [
      { value: "phone", label: "Phone call" },
      { value: "whatsapp", label: "WhatsApp message" },
      { value: "email", label: "Email" },
      { value: "video", label: "Video call (Zoom / Google Meet)" },
    ],
  },
  {
    id: "contact_details_followup",
    section: "Getting in touch",
    order: 31,
    prompt: "Best phone, email, or other details for follow-up on this project",
    type: "short_text",
    required: true,
    placeholder: "e.g. phone, email, WhatsApp (whoever should receive updates)",
  },
];
